services:
  operator:
    # Option 1: Use the public Docker image (recommended for most users)
    # image: singularitynetwork/singularity-kyc-avs-operator:latest

    # Option 2: Build from source (for development or customization)
    build:
      context: ../
      dockerfile: docker/Dockerfile

    env_file:
      - ../.env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
